### ISSUE TITLE
'NoneType' object has no attribute 'prepare' Error When Using Symbol.translate

### ISSUE THREAD

**Issue by Marevdb** [ExtensityAI/symbolicai#79]
### Description
Using the Symbol.translate method results in an AttributeError: 'NoneType' object has no attribute 'prepare'. None of the example code provided in the GitHub installation guide seems to work as expected, raising similar errors. 

I followed the setup instructions very carefully and had multiple people verify the steps with me. I've tried various approaches, including testing different Python versions, but all other versions seem to have issues (mostly with the engine model). Python 3.7 is the only version where the engine doesn't throw initialization errors.

### Environment
- **Python version**: 3.7 (Conda environment)
- **symai version**: 0.2.18

```bash
pip install symbolicai
```

### Code
```Python
from symai import Symbol

S = Symbol("Welcome to our tutorial.")
print(S.translate('German'))
```

### ERROR output
```
ERROR: 'NoneType' object has no attribute 'prepare'
Traceback (most recent call last):
  File "/home/name/miniconda3/envs/test_lhd/lib/python3.7/site-packages/symai/functional.py", line 142, in _process_query
    rsp = _execute_query(engine, post_processor, wrp_self, wrp_params, return_constraint, args, kwargs)
  File "/home/name/miniconda3/envs/test_lhd/lib/python3.7/site-packages/symai/functional.py", line 40, in _execute_query
    engine.prepare(args, kwargs, wrp_params)
AttributeError: 'NoneType' object has no attribute 'prepare'
Sorry, I do not understand the given language.
```

### Request
Could you please provide guidance on resolving this issue and clarify if there are any additional steps, dependencies, or configurations required for the library to function as intended?

**Comment by futurisold** [comment]
Hi! 

Can you please try this `httpx` version: 
```bash
pip install httpx=0.27.2
```

Also, can you tell me what OS do you use?  And just to rule it out, can you please confirm there exists a `symai.config.json` in your `~/.symai` folder and it's properly configured?

Lastly, is this issue linked with #78?

**Comment by Marevdb** [comment]
Hi! Thanks for your quick response.

As I'm using Python 3.7, `httpx` version 0.27.2 is not compatible, so I installed `httpx==0.24.1`. However, this has not resolved the issue.

I’m running Ubuntu 24.04.1 LTS through WSL. My `symai.config.json` file is located in the `~/.symai` folder, where I’ve copied the example configuration and added my keys and models for the neurosymbolic and symbolic engines.

Regarding your last question: my issue is indeed related to issue #78. However, in that case, I was working with higher Python versions (tried in both WSL and Windows, all in Conda environments). The issue there was that the engine would not initialize.

Let me know if additional details would help!

**Comment by futurisold** [comment]
Hi! Thanks for your patience. Unfortunately, we only support Python versions 3.10 and above. Please make sure you're using an environment running at least Python 3.10.

At the moment, there's an issue that needs fixing regarding the `httpx` version, which should be set to `0.27.2`. Additionally, installing via `pypy` isn't supported right now, but I'll patch that later today.

In the meantime, I recommend cloning the repository, navigating into it (`cd`), and running `pip install -e .`. Make sure you're using a conda environment with Python >=3.10.

First run takes a bit longer until everything gets cached.
